stevens = read.csv("stevens.csv")
str(stevens)
library(caTools)
set.seed(3000)
split = sample.split(stevens$Reverse, SplitRatio = 0.7)
Train = subset(stevens, split == TRUE)
Test = subset(stevens, split == FALSE)
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
StevensTree = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(minbucket = 25))
library(rpart.plot)
prp(StevensTree)
PredictCART = predict(StevensTree, newdata=Test, type="class")
table(Test$Reverse, PredictCART)
install.packages("ROCR")
library(ROCR)
predictROC = predict(StevensTree, newdata = Test)
predictROC
pred = prediction(predictROC[,2], Test$Reverse)
perf = performance(pred, "tpr", "fpr")
plot(perf)
